BookingAPI/src/Entity/Trip.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TripRepository")
 */
class Trip
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100, unique=true)
     * @Gedmo\Slug(fields={"title"})
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $start_date;

    /**
     * @ORM\Column(type="datetime")
     */
    private $end_date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $location;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $vacant_spaces;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\User", mappedBy="trips")
     */
    private $users;

    public function __construct()
    {
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        return $this->slug;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStartDate(\DateTimeInterface $start_date): self
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(\DateTimeInterface $end_date): self
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getVacantSpaces(): ?int
    {
        return $this->vacant_spaces;
    }

    public function setVacantSpaces(int $vacant_spaces): self
    {
        $this->vacant_spaces = $vacant_spaces;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->addTrip($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->contains($user)) {
            $this->users->removeElement($user);
            $user->removeTrip($this);
        }

        return $this;
    }
}

BookingAPI/src/Form/TripType.php
<?php

namespace App\Form;

use App\Entity\Trip;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TripType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('start_date')
            ->add('end_date')
            ->add('location')
            ->add('price')
            ->add('vacant_spaces')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Trip::class,
        ]);
    }
}

BookingAPI/src/Controller/TripController.php
<?php

namespace App\Controller;

use App\Entity\Trip;
use App\Form\TripType;
use App\Repository\TripRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/trip")
 */
class TripController extends AbstractController
{
    /**
     * @Route("/", name="trip_index", methods={"GET"})
     */
    public function index(TripRepository $tripRepository): Response
    {
        return $this->render('trip/index.html.twig', [
            'trips' => $tripRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="trip_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $trip = new Trip();
        $form = $this->createForm(TripType::class, $trip);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($trip);
            $entityManager->flush();

            return $this->redirectToRoute('trip_index');
        }

        return $this->render('trip/new.html.twig', [
            'trip' => $trip,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="trip_show", methods={"GET"})
     */
    public function show(Trip $trip): Response
    {
        return $this->render('trip/show.html.twig', [
            'trip' => $trip,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="trip_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Trip $trip): Response
    {
        $form = $this->createForm(TripType::class, $trip);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('trip_index');
        }

        return $this->render('trip/edit.html.twig', [
            'trip' => $trip,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="trip_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Trip $trip): Response
    {
        if ($this->isCsrfTokenValid('delete'.$trip->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($trip);
            $entityManager->flush();
        }

        return $this->redirectToRoute('trip_index');
    }
}

BookingAPI/templates/trip/_delete_form.html.twig
<form method="post" action="{{ path('trip_delete', {'id': trip.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ trip.id) }}">
    <button class="btn">Delete</button>
</form>

BookingAPI/templates/trip/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

BookingAPI/templates/trip/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Trip{% endblock %}

{% block body %}
    <h1>Edit Trip</h1>

    {{ include('trip/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('trip_index') }}">back to list</a>

    {{ include('trip/_delete_form.html.twig') }}
{% endblock %}

BookingAPI/templates/trip/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Trip index{% endblock %}

{% block body %}
    <h1>Trip index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Slug</th>
                <th>Title</th>
                <th>Description</th>
                <th>Start_date</th>
                <th>End_date</th>
                <th>Location</th>
                <th>Price</th>
                <th>Vacant_spaces</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for trip in trips %}
            <tr>
                <td>{{ trip.id }}</td>
                <td>{{ trip.slug }}</td>
                <td>{{ trip.title }}</td>
                <td>{{ trip.description }}</td>
                <td>{{ trip.startDate ? trip.startDate|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ trip.endDate ? trip.endDate|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ trip.location }}</td>
                <td>{{ trip.price }}</td>
                <td>{{ trip.vacantSpaces }}</td>
                <td>
                    <a href="{{ path('trip_show', {'id': trip.id}) }}">show</a>
                    <a href="{{ path('trip_edit', {'id': trip.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('trip_new') }}">Create new</a>
{% endblock %}

BookingAPI/templates/trip/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Trip{% endblock %}

{% block body %}
    <h1>Create new Trip</h1>

    {{ include('trip/_form.html.twig') }}

    <a href="{{ path('trip_index') }}">back to list</a>
{% endblock %}

BookingAPI/templates/trip/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Trip{% endblock %}

{% block body %}
    <h1>Trip</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ trip.id }}</td>
            </tr>
            <tr>
                <th>Slug</th>
                <td>{{ trip.slug }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ trip.title }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ trip.description }}</td>
            </tr>
            <tr>
                <th>Start_date</th>
                <td>{{ trip.startDate ? trip.startDate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>End_date</th>
                <td>{{ trip.endDate ? trip.endDate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Location</th>
                <td>{{ trip.location }}</td>
            </tr>
            <tr>
                <th>Price</th>
                <td>{{ trip.price }}</td>
            </tr>
            <tr>
                <th>Vacant_spaces</th>
                <td>{{ trip.vacantSpaces }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('trip_index') }}">back to list</a>

    <a href="{{ path('trip_edit', {'id': trip.id}) }}">edit</a>

    {{ include('trip/_delete_form.html.twig') }}
{% endblock %}